### ISSUE TITLE
ASN.1 grammer parse error 

### ISSUE THREAD

**Issue by jeick2008** [ikarso/3GPPTS36.413_AuthenticEshkinKot#1]
Get the latest asn1c (v0.9.29, https://github.com/vlm/asn1c.git), But Getting Error likes bellow:

[jeick@promote code]$ **asn1c -fcompound-names -gen-PER  -pdu=InitiatingMessage ../ASN/*.asn**
ASN.1 grammar parse error near line 119 (token "id-Bearers-SubjectToStatusTransfer-Item"): syntax error, unexpected TOK_identifier, expecting '}'
Cannot parse "../ASN/S1AP-IEs.asn"
[jeick@promote code]$ 

how to fix it ? thank you~

**Comment by ikarso** [comment]
Have you merged with PR #125 and #99 ? You still need to do it until @vlm have merged either #125 and #99 or #115 into his master.
(I have not tried to merge v0.9.29 with the PRs yet)

**Comment by jeick2008** [comment]
Thank you for your hard working.  With https://github.com/mouse07410/asn1c, it works well.
thank you,
